### ISSUE TITLE
Cannot install testmon without pandoc installed, version from apt doesn't work

### ISSUE THREAD

**Issue by DRMacIver** [tarpas/testmon#1]
[You have setup\_requires for setuptools-markdown](https://github.com/tarpas/testmon/blob/master/setup.py#L21), which requires pandoc to be installed on any machine setup.py runs on. This includes any machine that tries to install the package from pip.

As a result when I tried to install testmon from pip, first it failed because I didn't have pandoc installed, then it failed because something about the default pandoc install from apt doesn't work with this and complains about a missing format - I don't know whether it's because markdown isn't supported, rst isn't supported, or what. I don't really feel like debugging pandoc right now especially when I'm pretty sure it's going to require me to update my Haskell toolchain to get it working.

All of this seems very unnecessary and likely to be causing other people problems too. I admit RST is a bit of an annoying format, but avoiding it doesn't seem worth this hassle. Couldn't you either precompile your README to rst as part of the package build, or just write it in RST in the first place (github supports READMEs in RST natively, so that won't cause you a problem)?

**Comment by tarpas** [comment]
You're right. This was a last minute change and not a good one. We'll just
do RST as you suggest. I uploaded a new version to PyPI which installs fine
on my machine. If there are no more complaints soon with that one, I'll
push to GitHub.

**Comment by DRMacIver** [comment]
Sorry, still doesn't work. :-( different bug this time: 

    running install_data    
    error: can't copy 'README.md': doesn't exist or not a regular file

**Comment by DRMacIver** [comment]
Ah, that might have been a cached version. I just tried it with --no-cache and it worked this time.
