### ISSUE TITLE
docstring changes

### ISSUE THREAD

**Issue by schettino72** [tarpas/testmon#18]
It seems that just changing the docstring of a class or function is enough to trigger the re-execution of all tests that use the class/object. 

I would expect to only re-execute tests that access the `MyClass.__doc__`

**Comment by tarpas** [comment]
This is by design. MyClass.__doc__ can be directly and indirectly accessed in infinite ways, and testmon doesn't try to follow code logic. I'll write a blog post what we try to achieve and what not soon.

**Comment by tarpas** [comment]
As said, this is by design. testmon doesn't try to determine which tests read and process MyClass.__doc__ and which don't so any test which imported MyClass will be re-executed.
Promised explanation of what testmon does: 
https://github.com/tarpas/testmon/wiki/Determining-affected-tests
