### ISSUE TITLE
set-up travis-ci

### ISSUE THREAD

**Issue by tarpas** [tarpas/testmon#9]
Travis-ci is allegedly the most mature.
I'm open to other providers (like drone.io), especially if they sponsor customization of testmon for their (or any CI) needs :). 
The initial support should be for 
* python 2.7 
* python 3.newest
* coverage<4.0
* pytest<2.7
* pytest>=2.7

**Comment by public** [comment]
I've got the basics of this setup over here https://github.com/public/testmon/pull/1 but not all the tests currently seem to pass. Both failures are the same

```
_________________________________________________________ TestmonDeselect.test_easy _________________________________________________________
Traceback (most recent call last):
  File "/home/alexs/code/testmon/test/test_testmon.py", line 183, in test_easy
    node_data = config.cache.get(TESTS_CACHE_KEY, {})
AttributeError: 'Config' object has no attribute 'cache'
```

**Comment by tarpas** [comment]
It's quite odd that I didn't see it locally.  I fixed it and merged your branch.. Thanks!

**Comment by public** [comment]
Excellent, thank you :)
